export const RouterLinks = {
  LOGIN: "/login",
  REGISTER: "/register",
  HOME_PAGE: "/",
  BAO_CAO_DOANH_THU: "/baocao/doanhthu",
  BAO_CAO_MAT_HANG: "/baocao/mathang",
  BAO_CAO_KHO_HANG: "/baocao/khohang",
  BAO_CAO_TAI_CHINH: "/baocao/taichinh",
  BAO_CAO_NHAN_VIEN: "/baocao/nhanvien",
  MAT_HANG: "/mathang/danh_sach_mat_hang",
  DS_MAT_HANG: "mathang/danhsachmathang",
  THUC_DON: "/mathang/thucdon",
  DANH_MUC: "/mathang/danhmuc",
  LUA_CHON: "/mathang/luachon",
  COMBO: "/mathang/combo",
  DAT_BAN: "/datban",
  KHO_HANG: "/khohang/danh_sach_ton_kho",
  NHAP_KHO: "/khohang/nhapkho",
  KIEM_KE: "/khohang/kiemke",
  KHUYEN_MAI: "/khuyenmai",
  DANH_SACH_KHACH_HANG: "/khachhang/danhsachkhachhang"
};
